<!DOCTYPE html>
<html>
<head>
   <link rel='stylesheet' type='text/css' href='styles.css'> </link>
   <script type='text/javascript' src='mootools-core.js'> </script>
   <script type='text/javascript' src='mootools-HtmlTable.Zebra.js'> </script>
   <script type='text/javascript' src='JS/Utils/Utils.js'> </script>
   <script type='text/javascript' src='JS/Utils/POSITION.js'> </script>
   <script type='text/javascript' src='JS/Utils/HasOptions.js'> </script>
   <script type='text/javascript' src='JS/Utils/Resizer.js'> </script>
   <script type='text/javascript' src='JS/Divisions/SessionTemplate.js'> </script>
   <script type='text/javascript' src='JS/Divisions/Division.js'> </script>
   <script type='text/javascript' src='JS/Divisions/DivisionSuite.js'> </script>
   <script type='text/javascript' src='JS/Divisions/Set.js'> </script>
   <script type='text/javascript' src='JS/Divisions/Sets.js'> </script>
   <script type='text/javascript' src='JS/Divisions/Exercise.js'> </script>
   <script type='text/javascript' src='JS/Divisions/RecordField.js'> </script>
   <script type='text/javascript' src='JS/Divisions/INPUT.js'> </script>
   <script type='text/javascript' src='JS/Divisions/SYSTEM.js'> </script>
   <script type='text/javascript' src='JS/Divisions/Target.js'> </script>
   <script type='text/javascript' src='JS/Divisions/TargetRange.js'> </script>
   <script type='text/javascript' src='JS/Divisions/TargetString.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/Panel.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/Table.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/List.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/ListElement.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/SessionDivisions.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/SessionDivisionsElement.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/ClickablePanel.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/BorderedPanel.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/Button.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/Label.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/DropDownMenu.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/DropDownMenuUnfolded.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/DropDownElement.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/DropDownMenuItem.js'> </script>
   <script type='text/javascript' src='JS/Display/Containers/SetRecords.js'> </script>
   <script type='text/javascript' src='JS/SessionManager.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/ScreenManager.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/Screen.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/SCREEN.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/SCREEN_EVENT.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/SessionScreen.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/ExerciseScreen/DataEntry.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/ExerciseScreen/ExerciseScreen.js'> </script>
   <script type='text/javascript' src='JS/Display/Screens/ButtonManager.js'> </script>
</head>
<body>
</body>
<?php require 'loadSession.php'; ?>
</html>
