<!DOCTYPE html>
<html>
<head>
   <link rel='stylesheet' type='text/css' href='styles.css'> </link>
   <script type='text/javascript' src='mootools-core.js'> </script>
   <script type='text/javascript' src='mootools-HtmlTable.Zebra.js'> </script>
   <script type='text/javascript' src='Utils.js'> </script>
   <script type='text/javascript' src='Divisions.js'> </script>
   <script type='text/javascript' src='Containers.js'> </script>
   <script type='text/javascript' src='SessionManager.js'> </script>
   <script type='text/javascript' src='Screens.js'> </script>
</head>
<body>
</body>
<?php require 'loadSession.php'; ?>
</html>
